//! The **pure core** (WPM-D3–D5): every lifecycle state machine, the
//! leave / time / scheduling arithmetic, the org-chart cycle check,
//! payslip arithmetic, and benchmark flags — DB-free, clock-free, and
//! exhaustively unit-tested. Controllers wire these; they never
//! re-implement them.

pub mod access;
pub mod adjustments;
pub mod announcements;
pub mod appraisal;
pub mod assessment;
pub mod benchmark;
pub mod capability;
pub mod capacity;
pub mod career;
pub mod change;
pub mod contact_details;
pub mod cost;
pub mod cover;
pub mod cpd;
pub mod csv;
pub mod directory;
pub mod emergency;
pub mod engagement;
pub mod equality_monitoring;
pub mod ergonomics;
pub mod esco;
pub mod expenses;
pub mod flexible_working;
pub mod framework;
pub mod framework_roles;
pub mod gap;
pub mod grade;
pub mod groups;
pub mod health_requirements;
pub mod insights;
pub mod job_levels;
pub mod learning;
pub mod leave;
pub mod lifecycle;
pub mod lms;
pub mod metrics;
pub mod mobility;
pub mod movements;
pub mod notify;
pub mod org;
pub mod org_access;
pub mod pay_position;
pub mod pay_scale;
pub mod payroll;
pub mod planning;
pub mod privacy;
pub mod pulse;
pub mod resignation;
pub mod roles;
pub mod rota;
pub mod self_service;
pub mod skill_gap;
pub mod skill_merge;
pub mod talent;
pub mod time_off;
pub mod tokens;
pub mod training;
pub mod wellbeing;
pub mod workforce;
pub mod working_time;
