#!/usr/bin/env python3
"""Generate spec/implementation-status.md from the repository itself.

Run from anywhere: `python3 scripts/status.py` writes the file;
`python3 scripts/status.py --check` exits 1 if the committed file is stale.
Every number is counted from files by this script, never typed by hand. They
are counts of what is declared, not of what passes: whether the tests pass is
what CI reports.
"""
import glob
import os
import re
import subprocess
import sys

ROOT = subprocess.run(
    ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
).stdout.strip()
API = "workforce-planning-management-api-with-rust"
UI = "workforce-planning-management-ui-with-svelte"
OUT = os.path.join(ROOT, "spec", "implementation-status.md")


def read(*parts):
    with open(os.path.join(ROOT, *parts), encoding="utf-8") as handle:
        return handle.read()


def paths(pattern):
    return sorted(glob.glob(os.path.join(ROOT, pattern), recursive=True))


def count_in(pattern, regex, flags=0):
    total = 0
    for path in paths(pattern):
        with open(path, encoding="utf-8") as handle:
            total += len(re.findall(regex, handle.read(), flags))
    return total


def tasks():
    text = read("spec", "tasks.md")
    done = re.findall(r"^- \[x\] WPM-T(\d+)", text, re.M)
    open_ = re.findall(r"^- \[[ ~]\] WPM-T(\d+)", text, re.M)
    return len(done), len(open_), max((int(n) for n in done), default=0)


def build():
    done, pending, last_done = tasks()
    rows = [
        ("Tasks done in `spec/tasks.md`", done),
        ("Tasks not done (open or proposed)", pending),
        ("Highest task number marked done", f"WPM-T{last_done}"),
        ("Database migrations", len(paths(f"{API}/migration/src/m2*.rs"))),
        ("Controllers", len(paths(f"{API}/src/controllers/*.rs")) - 1),
        ("Pure rule modules", len(paths(f"{API}/src/rules/*.rs")) - 1),
        ("OpenAPI paths", count_in(f"{API}/src/openapi.rs", r'^\s*"/[^"]*":\s*\{', re.M)),
        ("Rust unit tests (`#[test]` in `src/`)", count_in(f"{API}/src/**/*.rs", r"#\[test\]")),
        (
            "Rust request tests (`tests/requests/`)",
            count_in(f"{API}/tests/requests/*.rs", r"#\[tokio::test\]"),
        ),
        (
            "Rust test binaries beside the request suite",
            len([p for p in paths(f"{API}/tests/*.rs") if not p.endswith("mod.rs")]),
        ),
        ("Front-end unit test files", len(paths(f"{UI}/tests/unit/*.test.ts"))),
        (
            "Front-end unit tests (`it(` / `test(`)",
            count_in(f"{UI}/tests/unit/*.test.ts", r"^\s*(?:it|test)\(", re.M),
        ),
        (
            "Playwright tests (`test(`)",
            count_in(f"{UI}/tests/e2e/*.spec.ts", r"^\s*test\(", re.M),
        ),
        ("Front-end pages (`+page.svelte`)", len(paths(f"{UI}/src/routes/**/+page.svelte"))),
        ("Content locales", len(paths(f"{UI}/content/locales/*/ui.json"))),
        (
            "Topic files in `spec/` (not counting this one)",
            len([p for p in paths("spec/*.md") if not p.endswith("implementation-status.md")]),
        ),
    ]
    lines = [
        "# Implementation status",
        "",
        "<!-- Generated by scripts/status.py. Do not edit by hand. -->",
        "",
        "Every number below is counted from the files in this repository by",
        "`scripts/status.py`. They count what is **declared**, not what passes:",
        "whether the tests pass is what CI reports. CI regenerates this file and",
        "fails if the committed copy is stale (`python3 scripts/status.py --check`).",
        "",
        "| Measure | Count |",
        "| --- | ---: |",
    ]
    lines += [f"| {name} | {value} |" for name, value in rows]
    lines.append("")
    return "\n".join(lines)


def main():
    text = build()
    if "--check" in sys.argv:
        current = read("spec", "implementation-status.md") if os.path.exists(OUT) else ""
        if current != text:
            print("spec/implementation-status.md is stale; run: python3 scripts/status.py")
            return 1
        print("spec/implementation-status.md is current")
        return 0
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(text)
    print(f"wrote {os.path.relpath(OUT, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
