// Generate static/admin/config.yml (Sveltia CMS) from the English UI
// strings, and keep the locale files in the nested shape the CMS edits.
//
//   node scripts/cms-config.mjs          write static/admin/config.yml
//   node scripts/cms-config.mjs --check  fail if it is out of date
//
// Why nested: the CMS cannot edit a flat `{"nav.workers": "…"}` file
// (its key-value field forbids dots in keys), so each locale's
// `content/locales/<locale>/ui.json` nests on the dots —
// `{"nav": {"workers": "…"}}` — and `i18n.svelte.ts` flattens it back
// to dotted keys at build time. Every key in en-001 becomes a text
// field (optional, so a regional locale can hold just its overrides);
// add a key there, rerun this, and the CMS offers it.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const localesDir = path.join(root, "content/locales");
const locales = fs.readdirSync(localesDir).sort();
const source = JSON.parse(
  fs.readFileSync(path.join(localesDir, "en-001/ui.json"), "utf8"),
);

const label = (name) => name.replace(/([a-z])([A-Z])/g, "$1 $2").replace(/^./, (c) => c.toUpperCase());
const q = (s) => JSON.stringify(s);

/** Nested object -> Sveltia field list (indented YAML lines). */
function fields(node, indent) {
  const pad = " ".repeat(indent);
  const out = [];
  for (const [name, value] of Object.entries(node)) {
    if (typeof value === "string") {
      const widget = value.length > 80 ? "text" : "string";
      out.push(`${pad}- { name: ${q(name)}, label: ${q(label(name))}, widget: ${widget}, required: false, i18n: true }`);
    } else {
      out.push(`${pad}- name: ${q(name)}`, `${pad}  label: ${q(label(name))}`, `${pad}  widget: object`, `${pad}  collapsed: true`, `${pad}  required: false`, `${pad}  i18n: true`, `${pad}  fields:`, ...fields(value, indent + 4));
    }
  }
  return out;
}

export function config() {
  return [
    "# GENERATED by scripts/cms-config.mjs from content/locales/en-001/ui.json — do not edit.",
    "# Sveltia CMS: edit at /<locale>/admin/ (e.g. /en-001/admin/). Strings live in content/locales/<locale>/ui.json.",
    "backend:",
    "  name: github",
    "  repo: workforce-planning-management/workforce-planning-management",
    "  branch: main",
    "",
    "# Sveltia CMS needs a media folder even though this site has no media.",
    "media_folder: workforce-planning-management-ui-with-svelte/static/assets",
    "public_folder: /assets",
    "",
    "i18n:",
    "  structure: multiple_folders",
    "  locales: [" + locales.join(", ") + "]",
    "  default_locale: en-001",
    "",
    "collections:",
    "  - name: ui",
    "    label: Interface strings",
    "    i18n: true",
    "    files:",
    "      - name: ui",
    "        label: Interface strings",
    "        i18n: true",
    "        file: workforce-planning-management-ui-with-svelte/content/locales/{{locale}}/ui.json",
    "        format: json",
    "        fields:",
    ...fields(source, 10),
    "",
  ].join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const target = path.join(root, "static/admin/config.yml");
  const text = config();
  if (process.argv.includes("--check")) {
    if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== text) {
      console.error("static/admin/config.yml is out of date: run `pnpm cms-config`");
      process.exit(1);
    }
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, text);
  }
}
